set-option -g prefix M-z
bind-key M-z send-prefix
unbind-key C-b

bind-key -n C-S-Right next-window
bind-key -n C-S-Left previous-window

bind-key -n C-Right resize-pane -R 10
bind-key -n C-Left resize-pane -L 10
bind-key -n C-Up resize-pane -U 10
bind-key -n C-Down resize-pane -D 10
unbind-key M-Right
unbind-key M-Left
unbind-key M-Up
unbind-key M-Down 

set-option -g status-bg default
set-option -g status-justify centre
set-option -g status-position bottom
set-option -g default-terminal screen-256color
set-option -g automatic-rename off
set-option -g status-style bg=default,fg=white
#set-option -g status-left '#[fg=#5e5e5e][#{session_name}]'
#set-option -g status-right '#[fg=#5e5e5e]#(echo $(date "+%A %d %b"))'
set-option -g status-right '#(echo $(date "+%A %d %b"))'
set-option -g window-status-style fg=#5e5e5e
set-option -g window-status-current-format '#[bold,fg=white]#{window_index}:#[bold,fg=white]#{window_name}'
#set-option -g window-status-last-style fg=#858585

set -g mouse on 
#set -g set-titles-string '#{pane_title}'
set -g set-titles on

