#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

#killall pantallas.sh
#$HOME/.config/bspwm/scripts/pantallas.sh 

if [[ $(xrandr --listmonitors  | grep '1-1' | wc -l) -ge 1 ]]
then
  $HOME/.config/bspwm/scripts/nvidia.sh
else
  $HOME/.config/bspwm/scripts/intel_hybrid.sh
fi

$HOME/.config/polybar/launch.sh

bspc config border_width         2
bspc config border_radius        0
bspc config split_ratio          0.50
bspc config top_padding          0

#bspc config focused_border_color  '#9243e9'
#bspc config focused_border_color  '#6354bb'
#bspc config focused_border_color  '#83a598'
#bspc config focused_border_color '#ffb472'
#bspc config focused_border_color  '#b0b0b0'
bspc config focused_border_color  '#555555'
#bspc config focused_border_color  '#ff9a04'
#bspc config focused_border_color  '#fb4934'

#bspc config normal_border_color  '#000000'

#bspc config active_border_color  '#b0b0b0'

#bspc config presel_feedback_color  '#ff9a04'
#bspc config presel_feedback_color  '#101010'
#bspc config presel_feedback_color  '#9243e9'
#bspc config presel_feedback_color  '#a20000' 


#bspc config single_monocle  true
bspc config focus_follows_pointer 	true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_monitor		true
#bspc config pointer_follows_focus		true


#------ Rules --------

export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a gui-ApplicationLauncher state=floating

#----- Autostart -----

#hora
#sudo ntpd -qg &

#fondo
feh --bg-fill /home/michael/Imágenes/Fondos\ de\ Pantalla/39.jpg

#transparencia
#killall picom
#picom &
#picom --no-vsync &

#luz nocturna
$HOME/.config/bspwm/scripts/luz_nocturna.sh &

#quitar radios de las esquinas en monocle
#killall monocle.sh
#$HOME/.config/bspwm/scripts/monocle.sh &

#gaps
if [[ $(xrandr --listmonitors | wc -l) -gt 2 ]]
then
  bspc config window_gap 8
  python $HOME/.customizar.py -s 8.5
else
  bspc config window_gap 8
  python $HOME/.customizar.py -s 9.5
fi


#monitor principal
bspc desktop -f 1
bspc config pointer_follows_monitor		false
xsetroot -cursor_name left_ptr 
unclutter -idle 2.0 -root &
