#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &


if [[ $(xrandr --listmonitors  | grep '1-1' | wc -l) -ge 1 ]]
then
  $HOME/.config/bspwm/scripts/nvidia.sh
else
  $HOME/.config/bspwm/scripts/intel_hybrid.sh
fi


bspc config border_width         2
#bspc config border_radius        10

#bspc config focused_border_color  '#0094d9'
#bspc config focused_border_color  '#00b485'
#bspc config focused_border_color  '#b0b0b0'
#bspc config focused_border_color  '#ff9a04'
#bspc config focused_border_color   '#dca060'
#bspc config focused_border_color  '#D13516'
#bspc config focused_border_color  '#a20000'

#bspc config presel_feedback_color  '#ff9a04'
#bspc config presel_feedback_color  '#00fe2a'
bspc config presel_feedback_color  '#a20000' 

bspc config top-padding          22
bspc config split_ratio          0.50

#bspc config single_monocle  true
bspc config focus_follows_pointer 	true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_monitor		true
remove_disabled_monitors true
#bspc config pointer_follows_focus		true

$HOME/.config/polybar/launch.sh

#------ Rules --------

#bspc rule -a Firefox desktop=I

#----- Autostart -----

#hora
#sudo ntpd -qg &

#fondo
feh --bg-fill /home/michael/Imágenes/Fondos\ de\ Pantalla/15.jpg

#transparencia
picom --no-vsync &

#luz nocturna
$HOME/.config/bspwm/scripts/luz_nocturna.sh &

#quitar radios de las esquinas en monocle
killall monocle.sh
$HOME/.config/bspwm/scripts/monocle.sh &

#gaps
if [[ $(xrandr --listmonitors | wc -l) -gt 2 ]]
then
  bspc config window_gap 10
  python $HOME/.customizar.py -s 9
else
  bspc config window_gap 10
  python $HOME/.customizar.py -s 10
fi


#monitor principal
bspc desktop -f I
bspc config pointer_follows_monitor		false
xsetroot -cursor_name left_ptr 
unclutter -idle 3.0 -root &
