[general]
import = [ "/home/michael/.config/alacritty/themes/Badwolf.toml",]

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 11.0

[mouse]
hide_when_typing = true

[window]
opacity = 1.0
startup_mode = "maximized"

[font.bold]
family = "JetBrains Mono ExtraBold Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono ExtraBold Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono ExtraBold Nerd Font"
style = "Bold"

[window.position]
x = 1080
y = 0

[window.padding]
x = 15
y = 15
