
[bar/primary]
monitor = HDMI1
width = 100%
;height = 26
height = 22
2orner-radius = 0
fixed-center = true 
bottom = false
;bottom = true

wm-restack = bspwm
enable-ipc = true

background = ${colors.bg}
foreground = ${colors.fg}

line-size = 0
line-color = #f00

border-size = 0
border-color = #00000000

padding-left = 0
padding-right = 0

module-margin-left = 0
module-margin-right = 0

;font-0 = Spleen:bold:pixelsize=11;2
;font-1 = unifont:fontformat=truetype:size=8:antialias=false;2
;font-2 = Spleen:pixelsize=8;1
;font-3 = Spleen:pixelsize=9;3
;font-4 = Spleen:pixelsize=10;2

;font-0 = White Rabbit:bold:pixelsize=9;2
;font-1 = unifont:fontformat=truetype:size=8:antialias=false;2
;font-2 = White Rabbit:pixelsize=8;1
;font-3 = White Rabbot:pixelsize=9;3
;font-4 = White Rabbit:pixelsize=10;2

;font-0 = TerminessTTF Nerd Font:bold:pixelsize=11;1
;font-1 = unifont:fontformat=truetype:size=8:antialias=false;2
;font-2 = TerminessTTF Nerd Font:bold:pixelsize=8;1
;font-3 = TerminessTTF Nerd Font:bold:pixelsize=11;2
;font-4 = TerminessTTF Nerd Font:bold:pixelsize=12;2

;font-0 = JetBrains Mono Medium Nerd Font:pixelsize=8.9;1
;font-1 = unifont:fontformat=truetype:size=8:antialias=false;2
;font-2 = JetBrains Mono Medium Nerd Font:pixelsize=8;1
;font-3 =  JetBrains Mono Medium Nerd Font:pixelsize=10;2
;font-4 = JetBrains Mono Medium Nerd Font:pixelsize=10;2

;font-0 = SpaceMono NF:bold:pixelsize=9;2
;font-1 = unifont:fontformat=truetype:size=8:antialias=false;2
;font-2 = SpaceMono NF:bold:pixelsize=8;2
;font-3 =  SpaceMono NF:bold:pixelsize=11;3
;font-4 = SpaceMono NF:bold:pixelsize=11;2

font-0 = JetBrains Mono ExtraBold Nerd Font:pixelsize=8.9;2
font-1 = unifont:fontformat=truetype:size=8:antialias=false;2
font-2 = JetBrains Mono ExtraBold Nerd Font:pixelsize=8;2
font-3 =  JetBrains Mono ExtraBold Nerd Font:pixelsize=11;3
font-4 = JetBrains Mono ExtraBold Nerd Font:pixelsize=10;2

;font-0 = JetBrains Mono ExtraBold Nerd Font:pixelsize=9;2
;font-1 = unifont:fontformat=truetype:size=8:antialias=false;2
;font-2 = JetBrains Mono ExtraBold Nerd Font:pixelsize=8;1
;font-3 =  JetBrains Mono ExtraBold Nerd Font:pixelsize=12;2
;font-4 = JetBrains Mono ExtraBold Nerd Font:pixelsize=11;2

font-5 = JetBrains Mono ExtraBold Nerd Font:pixelsize=30;7
font-6 = JetBrains Mono ExtraBold Nerd Font:pixelsize=13;3

;modules-left = bspwm sep wlan2 pacman-updates
;modules-center = xwindow1
;modules-right = sep wlan1 bluetooth pulseaudio1 sep weather_icon weather date pomodoro 

;modules-left = powermenu bspwm xwindow1
;modules-center = 
;modules-right = sep wlan2 sep2 sep memory2 cpu2 pacman-updates sep2 sep wlan1 bluetooth bluetooth_device pulseaudio1 sep2 sep weather_icon weather date sep2 pomodoro  

modules-left = pomodoro powermenu bspwm  xwindow1
modules-center =
modules-right = sep4 pacman-updates wlan2 sep3 cpu2 memory2 sep2 wlan1 bluetooth pulseaudio1 sep1 weather_icon weather date 

tray-position = left
tray-padding = 2
cursor-click = pointer
cursor-scroll = ns-resize

[bar/primary_nvidia]
inherit = bar/primary
monitor = HDMI-1-1

[bar/secondary]
monitor = eDP1
width = 100%
height = 28
radius = 0
fixed-center = true 

wm-restack = bspwm
enable-ipc = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0
line-color = #f00

border-size = 0
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin-left = 0
module-margin-right = 1

font-0 = jetbrains mono extrabold nerd font:pixelsize=12;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;2
font-2 = JetBrains Mono ExtraBold Nerd Font:pixelsize=8;1
font-3 = agave nerd font:pixelsize=13;4
font-4 = JetBrains Mono ExtraBold Nerd Font:pixelsize=12;1

#modules-left = bspwm
modules-center = bspwm  
#modules-right = fs-root fs-mnt sep gpu2 cpu1 memory2 swap sep wlan2


#tray-position = right
#tray-padding = 0
cursor-click = pointer
cursor-scroll = ns-resize

[bar/secondary2]
inherit = bar/secondary
monitor = DP-1-0
height = 22

font-0 = JetBrains Mono ExtraBold Nerd Font:pixelsize=9;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;2
font-2 = JetBrains Mono ExtraBold Nerd Font:pixelsize=8;1
font-3 = Agave Nerd Font:pixelsize=12;1
font-4 = JetBrains Mono ExtraBold Nerd Font:pixelsize=12;1


[bar/secondary_nvidia]
inherit = bar/secondary
monitor = eDP-1-1

[bar/laptop]
monitor = eDP1
width = 100%
height = 26
radius = 0
fixed-center = true 
bottom = false
;bottom = true

wm-restack = bspwm
enable-ipc = true

background = ${colors.bg}
foreground = ${colors.fg}

line-size = 0
line-color = #f00

border-size = 0
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin-left = 0
module-margin-right = 0

;font-0 = jetbrains mono extrabold nerd font:pixelsize=9;1
;font-1 = unifont:fontformat=truetype:size=7:antialias=false;2
;font-2 = jetbrains mono extrabold nerd font:pixelsize=9;1
;font-3 = agave nerd font:pixelsize=12;2
;font-4 = jetbrains mono extrabold nerd font:pixelsize=11;2
;font-5 = Agave Nerd Font:pixelsize=12;1

font-0 = JetBrains Mono ExtraBold Nerd Font:pixelsize=9;2
font-1 = unifont:fontformat=truetype:size=8:antialias=false;2
font-2 = JetBrains Mono ExtraBold Nerd Font:pixelsize=8;1
font-3 =  JetBrains Mono ExtraBold Nerd Font:pixelsize=10;3
font-4 = JetBrains Mono ExtraBold Nerd Font:pixelsize=11;2
font-5 = Agave Nerd Font:pixelsize=13;4

;font-0 = Spleen:bold:pixelsize=11;0
;font-1 = unifont:fontformat=truetype:size=8:antialias=false;2
;font-2 = Spleen:pixelsize=8;1
;font-3 = Spleen:pixelsize=9;3
;font-4 = Spleen:pixelsize=10;2


;modules-left = bspwm sep wlan2
;modules-center = xwindow2
;modules-right = wlan1 bluetooth pulseaudio1 brightness sep weather_icon weather date 

;modules-left = powermenu bspwm xwindow2
;modules-center = 
;modules-right = wlan2 sep memory2 cpu2 sep wlan1 bluetooth pulseaudio1 battery sep weather_icon weather date pomodoro 

modules-left = pomodoro powermenu bspwm  xwindow1
modules-center =
modules-right = sep4 pacman-updates wlan2 sep3 cpu2 memory2 sep2 wlan1 bluetooth pulseaudio1 brightness battery sep1 weather_icon weather date 

tray-position = right
tray-padding = 1
cursor-click = pointer
cursor-scroll = ns-resize

[bar/laptop_nvidia]
inherit = bar/laptop
monitor = eDP-1-1

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false

[global/wm]
margin-top = 0
margin-bottom = 0
include-file = $HOME/.config/polybar/modules.ini
include-file = $HOME/.config/polybar/themes/basic.ini