[module/pomodoro]
type = custom/script
interval = 3.5
exec = ~/.config/polybar/scripts/pomodoro.sh  
click-left = i3-gnome-pomodoro pause
click-right = i3-gnome-pomodoro resume
format-background = ${colors.bg5}
;foreground = ${colors.fg5}

[module/pacman-updates]
type = custom/script
format-prefix = "ﮮ "
format-prefix-font = 4
exec = ~/.config/polybar/scripts/updates.sh
interval = 600
format = "<label>  "
format-background = ${colors.bg4}
format-foreground = ${colors.fg4}

[module/weather]
type = custom/script
exec = python ~/.config/polybar/scripts/weather/weather.py 
interval = 300 
label-font = 1
format = "<label> "
format-background = ${colors.bg1}
format-foreground = ${colors.fg1}

[module/weather_icon]
type = custom/script
exec = python ~/.config/polybar/scripts/weather/weather_icon.py 
interval = 300 
label-font = 5
format = "<label>"
format-background = ${colors.bg1}
format-foreground = ${colors.fg1}

[module/bluetooth]
type = custom/script
;exec =  ~/.config/polybar/scripts/bluetooth/bluetooth1.sh 
;exec =  ~/.config/polybar/scripts/bluetooth/bluetooth2.sh 
exec =  ~/.config/polybar/scripts/bluetooth/bluetooth3.sh 
click-left = ~/.config/polybar/scripts/bluetooth/bluetooth_power.sh
interval = 5 
label-font = 4
format = "<label> "
format-background = ${colors.bg2}
format-foreground = ${colors.fg2}

[module/bluetooth_device]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth/device_name.sh
interval = 5 
format = "<label> "
format-background = ${colors.bg2}
format-foreground = ${colors.fg2}

[module/date]
type = internal/date
interval = 1.0
date = ""
time = " %a %d %b %H:%M:%S "
;time = "%a %d/%m/%Y %H:%M:%S"
date-alt = " %A "
time-alt = "%d/%m/%Y "
format = <label>
label = "%{A3: gnome-calendar:}%date%%time%%{A}" 
label-font = 5
;label-font = 4
format-background = ${colors.bg1}
format-foreground = ${colors.fg1}

[module/fecha]
type = custom/script
exec = echo " $(date '+%A %d-%m %H:%M')"
click-left = gnome-calendar
label-font = 5
interval = 30
background = ${colors.bg1}
foreground = ${colors.fg1}

[fs-base]
type = internal/fs
fixed-values = true
label-mounted = %mountpoint%: %free%

[module/fs-home]
inherit = fs-base
mount-0 = /home
label-mounted = "   %used% (%percentage_used%%)"
;label-mounted = " /home  %used% (%percentage_used%%)"
interval = 1

[module/fs-root]
inherit = fs-base
mount-0 = /
label-mounted = "   / %used% (%percentage_used%%)"
interval = 1

[module/fs-mnt]
inherit = fs-base
mount-0 = /mnt
label-mounted = "   /mnt %used% (%percentage_used%%)"
label-unmounted = ""
interval = 1

[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
full-at = 98

format-charging = "<animation-charging><label-charging> "
format-charging-background = ${colors.bg2}
format-charging-foreground = ${colors.fg2}
;format-charging = "bat: <label-charging>"
;format-charging-foreground = {colors.fg2}

format-discharging = " <ramp-capacity><label-discharging> "
format-discharging-background = ${colors.bg2}
format-discharging-foreground = ${colors.fg2}
;format-discharging = " bat: <label-discharging>"
;format-discharging-foreground = {colors.fg2}

;format-full-prefix = "bat: "
format-full = " <ramp-capacity><label-full> "
format-full-background = ${colors.bg2}
format-full-foreground = ${colors.fg2}
;format-full-prefix-foreground = {colors.fg2}

ramp-capacity-0 = "   "
ramp-capacity-1 = "   "
ramp-capacity-2 = "   "
ramp-capacity-3 = "   "
ramp-capacity-4 = "   "

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = "   "
animation-charging-1 = "   "
animation-charging-2 = "   "
animation-charging-3 = "   "
animation-charging-4 = "   "
; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = "   "
animation-discharging-1 = "   "
animation-discharging-2 = "   "
animation-discharging-3 = "   "
animation-discharging-4 = "   "
; Framerate in milliseconds
animation-discharging-framerate = 500

[module/gpu1]
type = custom/script
exec = echo " gpu: $(.config/polybar/scripts/gpu/gpu1.sh)"
interval = 1

format = "<label> "
format-background = ${colors.bg3}
format-foreground = ${colors.fg3}

[module/gpu2]
type = custom/script
exec = echo " gpu [$(.config/polybar/scripts/gpu/gpu2.sh)]"
interval = 1

format = "<label> "
format-background = ${colors.bg3}
format-foreground = ${colors.fg3}

[module/cpu1]
type = internal/cpu
interval = 0.5 

; Available tokens:
;   %percentage% (default) - total cpu load averaged over all cores
;   %percentage-sum% - Cumulative load on all cores
;   %percentage-cores% - load percentage for each core
;   %percentage-core[1-9]% - load percentage for specific core
label = "%percentage%%"

; Spacing between individual per-core ramps
ramp-coreload-spacing = 0
ramp-coreload-font = 5
ramp-coreload-0 = " "  
ramp-coreload-1 = ▁
ramp-coreload-2 = ▂
ramp-coreload-3 = ▃
ramp-coreload-4 = ▄
ramp-coreload-5 = ▅
ramp-coreload-6 = ▆
ramp-coreload-7 = ▇
ramp-coreload-8 = █
;format-prefix = " cpu: "
;format-prefix-font = 1
;format-prefix-foreground = #ffffff 
;format-underline = #000000

;format = "<label> <ramp-coreload> "
format = "<ramp-coreload> "
format-background = ${colors.bg3}
format-foreground = ${colors.fg3}

[module/cpu2]
type = internal/cpu
interval = 0.5 

; Available tokens:
;   %percentage% (default) - total cpu load averaged over all cores
;   %percentage-sum% - Cumulative load on all cores
;   %percentage-cores% - load percentage for each core
;   %percentage-core[1-9]% - load percentage for specific core
format-prefix = "  "
format-prefix-font = 4
label = %percentage%%

;format = "cpu: <label> " 
format = "<prefix> (<label>) " 
format-background = ${colors.bg3}
format-foreground = ${colors.fg3}

[module/memory1]
type = internal/memory
interval = 2
label = " mem: %mb_used%"
#label = " mem: %percentage_used%% swap: %mb_swap_used%"
 
; Only applies if <bar-used> is used
bar-used-indicator =
bar-used-width = 7
bar-used-foreground-0 = #55aa55
bar-used-foreground-1 = #557755
bar-used-foreground-2 = #f5a70a
bar-used-foreground-3 = #ff5555
bar-used-fill = | 
bar-used-empty = |
bar-used-empty-foreground = #444444

;format = "<label> <bar-used> "
format = "<label> "
format-background = ${colors.bg3}
format-foreground = ${colors.fg3}

[module/memory2]
type = custom/script
exec = /home/michael/.config/polybar/scripts/memory/memory.sh
format = "<label> "
format-prefix = " 溜 "
format-prefix-font = 4
interval = 1

format-background = ${colors.bg3}
format-foreground = ${colors.fg3}
format-prefix-background = ${colors.bg3}
format-prefix-foreground = ${colors.fg3}

[module/swap]
type = custom/script
exec = /home/michael/.config/polybar/scripts/memory/swap.sh
interval = 1

format = "<label> "
format-background = ${colors.bg3}
format-foreground = ${colors.fg3}

[module/pulseaudio1]
type = internal/pulseaudio

format-volume = " <ramp-volume><label-volume> "
label-volume =  %percentage%%
label-volume-foreground = ${colors.fg2}

;label-muted = "婢 <muted>  " 
;label-muted = "vol: <muted>  " 
;label-muted-font= 1
;label-muted-foreground = #666

label-muted = "ﱝ "
label-muted-font = 7
label-muted-foreground = ${colors.fg2}

; Only applies if <ramp-volume> is used
ramp-volume-0 = "奄 "
ramp-volume-1 = "奔 "
ramp-volume-2 = "墳 "
ramp-volume-3 = " "
ramp-volume-font = 4
ramp-volume-foreground = ${colors.fg2}

format-volume-background = ${colors.bg2}
format-muted-background = ${colors.bg2}

[module/pulseaudio2]
type = internal/pulseaudio

format-volume = "<label-volume> "
label-volume = "  %percentage%%"
;label-volume = " vol:%percentage%%"
label-volume-foreground = ${colors.fg2}

label-muted = "  " 
;label-muted = " muted" 
label-muted-font = 5
#label-muted-foreground = #666
label-muted-foreground =  ${colors.fg2}

;format-volume-background = ${colors.bg2}
format-volume-background = ${colors.bg2}

[module/bspwm]
type = internal/bspwm
#pin-workspaces = false

;label-focused =   
;label-occupied =  
;label-urgent =  
;label-empty =  

label-focused =  "[%name%]" 
;label-focused =  " %name% " 
label-occupied =  " %name% "  
label-urgent =  " %name%! "  
;label-empty =  " %name% " 
label-empty =  "" 

;label-focused-padding = 0
;label-occupied-padding = 0
;label-urgent-padding = 0
;label-empty-padding = 0
label-focused-padding = 1
label-occupied-padding = 1
label-urgent-padding = 1
label-empty-padding = 1

label-focused-foreground = ${colors.fg}
;label-focused-background = ${colors.focus}
;label-focused-background = #151515

;label-occupied-foreground = #828282 
label-occupied-foreground = ${colors.fg}

;label-urgent-foreground = ##fffe13
label-urgent-foreground = ${colors.alert}

label-empty-foreground = #828282

; Separator in between workspaces
; label-separator = |

label-song-maxlen = 25
label-song-ellipsis = true

[module/xwindow1]
type = internal/xwindow
label =	"%title:0:120:...%"
format = "<label> "
label-font = 1
label-margin-left = 1
format-foreground = ${colors.fg}

label-empty = " Escritorio "
label-empty-font = 1
label-empty-foreground = ${colors.fg}

[module/xwindow2]
type = internal/xwindow
label =	"%title:0:150:...%"
format = "<label> "
label-font = 1
label-margin-left = 1
format-foreground = ${colors.fg}

label-empty = "  Escritorio "
label-empty-font = 1
label-empty-foreground = ${colors.fg}

[module/wlan1]
type = internal/network
interface = wlp47s0 
interval = 3

format-connected = "<label-connected> "
format-connected-background = ${colors.bg2}
format-connected-foreground = ${colors.fg2}
label-connected = "%{A1:alacritty -e nmtui:}   %{A}"
;label-connected = "%{A1:alacritty -e nmtui:}   %essid% %{A}"
;label-connected = "%{A1:alacritty -e nmtui:}net: %essid% %{A}"

format-disconnected = "<label-disconnected> "
format-disconnected-background = ${colors.bg2}
format-disconnected-foreground = ${colors.fg2}
label-disconnected = "%{A1:alacritty -e nmtui:} 睊  %{A}"
;label-disconnected = "%{A1:alacritty -e nmtui:} 睊 no cennection %{A}"
;label-disconnected = "%{A1:alacritty -e nmtui:}net: off  %{A}"
;label-disconnected-foreground = ${colors.foreground-alt}

[module/wlan2]
type = internal/network
interface = wlp47s0 
interval = 1

format-connected = "<label-connected> "
format-connected-background = ${colors.bg4}
format-connected-foreground = ${colors.fg4}
;label-connected = "%{A1:alacritty -e nmtui:} %upspeed%   %downspeed%%{A}"
label-connected = "%{A1:alacritty -e nmtui:} %upspeed%   %downspeed%%{A}"
;label-connected = "%{A1:alacritty -e nmtui:} %upspeed%   %downspeed%%{A}"
;label-connected = "%{A1:alacritty -e nmtui:}out: %upspeed%  in: %downspeed%%{A}"

format-disconnected = "<label-disconnected> "
format-disconnected-background = ${colors.bg4}
format-disconnected-foreground = ${colors.fg4}
;label-disconnected = "%{A1:alacritty -e nmtui:} 0 KB/s   0 KB/s%{A}"
label-disconnected = "%{A1:alacritty -e nmtui:} 0 KB/s   0 KB/s%{A}"
;label-disconnected = "%{A1:alacritty -e nmtui:} 0 KB/s   0 KB/s%{A}"
;label-disconnected = "%{A1:alacritty -e nmtui:}out: 0 KB/s  in: 0 KB/s%{A}"
;label-disconnected-foreground = ${colors.foreground-alt}

[module/brightness]
type = custom/script
exec = ~/.config/polybar/scripts/brightness.sh
scroll-up = brightnessctl set +5%
scroll-down = brightnessctl set 5%-
interval = 3

format = "<label> "
format-background = ${colors.bg2}
format-foreground = ${colors.fg2}

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 1

label-open = "    " 
label-open-foreground = ${colors.fg}
label-close = | X
label-close-foreground =  ${colors.fg}
label-separator = |
label-separator-foreground =  ${colors.fg}

menu-0-0 =  apagar
menu-0-0-exec = menu-open-1
menu-0-1 = reiniciar
menu-0-1-exec = menu-open-2
menu-0-2 = suspender
menu-0-2-exec = menu-open-3
menu-0-3 = cerrar sesión |
menu-0-3-exec = menu-open-4

menu-1-0 = apagar
menu-1-0-exec = poweroff
menu-1-1 = cancelar |
menu-1-1-exec = menu-open-0

menu-2-0 = reiniciar
menu-2-0-exec = reboot
menu-2-1 = cancelar |
menu-2-1-exec = menu-open-0

menu-3-0 = suspender
menu-3-0-exec = systemctl suspend
menu-3-1 = cancelar |
menu-3-1-exec = menu-open-0


menu-4-0 = cerrar sesión
menu-4-0-exec = bspc quit
menu-4-1 = cancelar |
menu-4-1-exec = menu-open-0

[sep]
type = custom/text
content = ""
content-font = 6

[module/sep1]
inherit = sep
content-foreground = ${colors.bg1} 
content-background = ${colors.bg2}

[module/sep2]
inherit = sep
content-foreground = ${colors.bg2} 
content-background = ${colors.bg3}

[module/sep3]
inherit = sep
content-foreground = ${colors.bg3} 
content-background = ${colors.bg4}

[module/sep4]
inherit = sep
content-foreground = ${colors.bg4} 
content-background = ${colors.bg}
